module.exports = [
	{name: "Department of State",
	 seal: "img/seal_department_of_state.png",
	 website: "https://www.state.gov/",
	 searchTerms: ['"Department of State"', '"Rex Tillerson"', '"Mike Pompeo"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'StateDept',
	},
	{name: "Department of Treasury",
	 seal: "img/seal_department_of_treasury.png",
	 website: "https://home.treasury.gov/",
	 searchTerms: ['"Department of Treasury"', '"Steve Mnuchin"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'USTreasury',
	},
	{name: "Department of Defense",
	 seal: "img/seal_department_of_defense.png",
	 website: "https://www.defense.gov/",
	 searchTerms: ['"Department of Defense"', '"James Mattis"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'DeptofDefense',
	},
	{name: "Attorney General",
	 seal: "img/seal_attorney_general.png",
	 website: "https://www.justice.gov/ag",
	 searchTerms: ['"Attorney General"', '"Jeff Sessions"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'thejusticedept',
	},
	{name: "Department of the Interior",
	 seal: "img/seal_department_of_the_interior.png",
	 website: "https://www.doi.gov/",
	 searchTerms: ['"Department of the Interior"', '"Ryan Zinke"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'Interior',
	},
	{name: "Department of Agriculture",
	 seal: "img/seal_department_of_agriculture.png",
	 website: "https://www.usa.gov/federal-agencies/u-s-department-of-agriculture",
	 searchTerms: ['"Department of Agriculture"', '"Sonny Perdue"', '"USDA"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'usda',
	},
	{name: "Department of Commerce",
	 seal: "img/seal_department_of_commerce.png",
	 website: "https://www.commerce.gov/",
	 searchTerms: ['"Department of Commerce"', '"Wilbur Ross"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'CommerceGov',
	},
	{name: "Department of Labor",
	 seal: "img/seal_department_of_labor.png",
	 website: "https://www.dol.gov/",
	 searchTerms: ['"Department of Labor"', '"Alex Acosta"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'USDOL',
	},
	{name: "Department of Health and Human Services",
	 seal: "img/seal_department_of_health_and_human_services.png",
	 website: "https://www.hhs.gov/",
	 searchTerms: ['"Department of Health and Human Services"', '"Eric Hargan"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'HHSGov',
	},
	{name: "Department of Housing and Urban Development",
	 seal: "img/seal_department_of_housing_and_urban_development.png",
	 website: "https://www.hud.gov/",
	 searchTerms: ['"Department of Housing and Urban Development"', '"Ben Carson"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'HUDgov',
	},
	{name: "Department of Transportation",
	 seal: "img/seal_department_of_transportation.png",
	 website: "https://www.transportation.gov/",
	 searchTerms: ['"Department of Transportation"', '"Elaine Chao"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'USDOT',
	},
	{name: "Department of Energy",
	 seal: "img/seal_department_of_energy.png",
	 website: "https://energy.gov/",
	 searchTerms: ['"Department of Energy"', '"Rick Perry"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'ENERGY',
	},
	{name: "Department of Education",
	 seal: "img/seal_department_of_education.png",
	 website: "https://www.ed.gov/",
	 searchTerms: ['"Department of Education"', '"Betsy DeVos"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'usedgov',
	},
	{name: "Department of Veterans Affairs",
	 seal: "img/seal_department_of_veterans_affairs.png",
	 website: "https://www.va.gov/",
	 searchTerms: ['"Department of Veterans Affairs"', '"David Shulkin"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'deptvetaffairs',
	 },
	 {name: "Department of Homeland Security",
	 seal: "img/seal_department_of_homeland_security.png",
	 website: "https://www.dhs.gov/",
	 searchTerms: ['"Department of Homeland Security"', '"Kirstjen Nielsen"'],
	 newsResults: [],
	 newsPageNumber: 1,
	 twitterUsername: 'DHSgov',
	}
]